In [1]:
import numpy as np

In [ ]:
A = np.array([
    [0, 1],
    [2, 3],
    [4, 5]
])

B = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])

In [3]:
np.dot(A, B)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [6]:
C = np.dot(A, B)

In [8]:
print(C)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [9]:
print(C.max())

47
